targets:
  $default:
    builders:
      freezed:
        generate_for:
          - "lib/**/*.dart"
          - "!lib/**/*.freezed.dart"
          - "!lib/**/*.g.dart"
        options:
          format: true
      json_serializable:
        generate_for:
          - "lib/**/*.dart"
          - "!lib/**/*.freezed.dart"
          - "!lib/**/*.g.dart"
        options:
          explicit_to_json: true
      riverpod_generator:
        generate_for:
          - "lib/*.dart"
          - "lib/**/*.dart"
          - "!lib/**/*.freezed.dart"
          - "!lib/**/*.g.dart"
      slang_build_runner:
        options:
          base_locale: pt-BR
          fallback_strategy: base_locale
          input_directory: lib/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/i18n
          output_file_name: strings.g.dart
          translate_var: t
          enum_name: AppLocale
          class_name: Translations
          locale_handling: false
          translation_class_visibility: public
          lazy: true
          flutter_integration: true
          namespaces: false
          string_interpolation: braces
          flat_map: true
          timestamp: false
          statistics: true
          missing_translation_strategy: fail
