// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsJobMapApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsJobMapApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsJobMapApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashJobMapApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashJobMapApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashJobMapApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMapRenderRequest: Hashable {
  var requestId: Int64
  var rendererSlot: Int64
  var widthPx: Int64
  var heightPx: Int64
  var widthPoints: Double
  var heightPoints: Double
  var nativeScale: Double
  var previewScale: Double
  var cameraLatitude: Double
  var cameraLongitude: Double
  var locationLatitude: Double
  var locationLongitude: Double
  var zoom: Double
  var radiusMeters: Double
  var radiusColorArgb: Int64
  var backgroundColorArgb: Int64
  var paddingBottomPoints: Double
  var styleJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMapRenderRequest? {
    let requestId = pigeonVar_list[0] as! Int64
    let rendererSlot = pigeonVar_list[1] as! Int64
    let widthPx = pigeonVar_list[2] as! Int64
    let heightPx = pigeonVar_list[3] as! Int64
    let widthPoints = pigeonVar_list[4] as! Double
    let heightPoints = pigeonVar_list[5] as! Double
    let nativeScale = pigeonVar_list[6] as! Double
    let previewScale = pigeonVar_list[7] as! Double
    let cameraLatitude = pigeonVar_list[8] as! Double
    let cameraLongitude = pigeonVar_list[9] as! Double
    let locationLatitude = pigeonVar_list[10] as! Double
    let locationLongitude = pigeonVar_list[11] as! Double
    let zoom = pigeonVar_list[12] as! Double
    let radiusMeters = pigeonVar_list[13] as! Double
    let radiusColorArgb = pigeonVar_list[14] as! Int64
    let backgroundColorArgb = pigeonVar_list[15] as! Int64
    let paddingBottomPoints = pigeonVar_list[16] as! Double
    let styleJson: String? = nilOrValue(pigeonVar_list[17])

    return NativeMapRenderRequest(
      requestId: requestId,
      rendererSlot: rendererSlot,
      widthPx: widthPx,
      heightPx: heightPx,
      widthPoints: widthPoints,
      heightPoints: heightPoints,
      nativeScale: nativeScale,
      previewScale: previewScale,
      cameraLatitude: cameraLatitude,
      cameraLongitude: cameraLongitude,
      locationLatitude: locationLatitude,
      locationLongitude: locationLongitude,
      zoom: zoom,
      radiusMeters: radiusMeters,
      radiusColorArgb: radiusColorArgb,
      backgroundColorArgb: backgroundColorArgb,
      paddingBottomPoints: paddingBottomPoints,
      styleJson: styleJson
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      rendererSlot,
      widthPx,
      heightPx,
      widthPoints,
      heightPoints,
      nativeScale,
      previewScale,
      cameraLatitude,
      cameraLongitude,
      locationLatitude,
      locationLongitude,
      zoom,
      radiusMeters,
      radiusColorArgb,
      backgroundColorArgb,
      paddingBottomPoints,
      styleJson,
    ]
  }
  static func == (lhs: NativeMapRenderRequest, rhs: NativeMapRenderRequest) -> Bool {
    return deepEqualsJobMapApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashJobMapApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMapFrames: Hashable {
  var textureId: Int64
  var widthPx: Int64
  var heightPx: Int64
  var previewTextureId: Int64
  var previewWidthPx: Int64
  var previewHeightPx: Int64
  var isFinal: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMapFrames? {
    let textureId = pigeonVar_list[0] as! Int64
    let widthPx = pigeonVar_list[1] as! Int64
    let heightPx = pigeonVar_list[2] as! Int64
    let previewTextureId = pigeonVar_list[3] as! Int64
    let previewWidthPx = pigeonVar_list[4] as! Int64
    let previewHeightPx = pigeonVar_list[5] as! Int64
    let isFinal = pigeonVar_list[6] as! Bool

    return NativeMapFrames(
      textureId: textureId,
      widthPx: widthPx,
      heightPx: heightPx,
      previewTextureId: previewTextureId,
      previewWidthPx: previewWidthPx,
      previewHeightPx: previewHeightPx,
      isFinal: isFinal
    )
  }
  func toList() -> [Any?] {
    return [
      textureId,
      widthPx,
      heightPx,
      previewTextureId,
      previewWidthPx,
      previewHeightPx,
      isFinal,
    ]
  }
  static func == (lhs: NativeMapFrames, rhs: NativeMapFrames) -> Bool {
    return deepEqualsJobMapApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashJobMapApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMapFinalFrame: Hashable {
  var requestId: Int64
  var rendererSlot: Int64
  var textureId: Int64
  var widthPx: Int64
  var heightPx: Int64
  var previewTextureId: Int64
  var previewWidthPx: Int64
  var previewHeightPx: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMapFinalFrame? {
    let requestId = pigeonVar_list[0] as! Int64
    let rendererSlot = pigeonVar_list[1] as! Int64
    let textureId = pigeonVar_list[2] as! Int64
    let widthPx = pigeonVar_list[3] as! Int64
    let heightPx = pigeonVar_list[4] as! Int64
    let previewTextureId = pigeonVar_list[5] as! Int64
    let previewWidthPx = pigeonVar_list[6] as! Int64
    let previewHeightPx = pigeonVar_list[7] as! Int64

    return NativeMapFinalFrame(
      requestId: requestId,
      rendererSlot: rendererSlot,
      textureId: textureId,
      widthPx: widthPx,
      heightPx: heightPx,
      previewTextureId: previewTextureId,
      previewWidthPx: previewWidthPx,
      previewHeightPx: previewHeightPx
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      rendererSlot,
      textureId,
      widthPx,
      heightPx,
      previewTextureId,
      previewWidthPx,
      previewHeightPx,
    ]
  }
  static func == (lhs: NativeMapFinalFrame, rhs: NativeMapFinalFrame) -> Bool {
    return deepEqualsJobMapApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashJobMapApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMapCapabilities: Hashable {
  var lowMemory: Bool
  var lowRamDevice: Bool
  var availableMemoryBytes: Int64
  var totalMemoryBytes: Int64
  var processorCount: Int64
  var thermalState: Int64
  var maxRendererSlots: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMapCapabilities? {
    let lowMemory = pigeonVar_list[0] as! Bool
    let lowRamDevice = pigeonVar_list[1] as! Bool
    let availableMemoryBytes = pigeonVar_list[2] as! Int64
    let totalMemoryBytes = pigeonVar_list[3] as! Int64
    let processorCount = pigeonVar_list[4] as! Int64
    let thermalState = pigeonVar_list[5] as! Int64
    let maxRendererSlots = pigeonVar_list[6] as! Int64

    return NativeMapCapabilities(
      lowMemory: lowMemory,
      lowRamDevice: lowRamDevice,
      availableMemoryBytes: availableMemoryBytes,
      totalMemoryBytes: totalMemoryBytes,
      processorCount: processorCount,
      thermalState: thermalState,
      maxRendererSlots: maxRendererSlots
    )
  }
  func toList() -> [Any?] {
    return [
      lowMemory,
      lowRamDevice,
      availableMemoryBytes,
      totalMemoryBytes,
      processorCount,
      thermalState,
      maxRendererSlots,
    ]
  }
  static func == (lhs: NativeMapCapabilities, rhs: NativeMapCapabilities) -> Bool {
    return deepEqualsJobMapApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashJobMapApi(value: toList(), hasher: &hasher)
  }
}

private class JobMapApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeMapRenderRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeMapFrames.fromList(self.readValue() as! [Any?])
    case 131:
      return NativeMapFinalFrame.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeMapCapabilities.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class JobMapApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeMapRenderRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMapFrames {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMapFinalFrame {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMapCapabilities {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class JobMapApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return JobMapApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return JobMapApiPigeonCodecWriter(data: data)
  }
}

class JobMapApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = JobMapApiPigeonCodec(readerWriter: JobMapApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol JobMapHostApi {
  func render(request: NativeMapRenderRequest, completion: @escaping (Result<NativeMapFrames, Error>) -> Void)
  func releaseTexture(textureId: Int64) throws
  func setScrollActive(active: Bool, allowReadyPreview: Bool) throws
  func readRenderCapabilities() throws -> NativeMapCapabilities
  func disposeFrames() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class JobMapHostApiSetup {
  static var codec: FlutterStandardMessageCodec { JobMapApiPigeonCodec.shared }
  /// Sets up an instance of `JobMapHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: JobMapHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let renderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.job_map.JobMapHostApi.render\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      renderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeMapRenderRequest
        api.render(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      renderChannel.setMessageHandler(nil)
    }
    let releaseTextureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.job_map.JobMapHostApi.releaseTexture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseTextureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let textureIdArg = args[0] as! Int64
        do {
          try api.releaseTexture(textureId: textureIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      releaseTextureChannel.setMessageHandler(nil)
    }
    let setScrollActiveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.job_map.JobMapHostApi.setScrollActive\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setScrollActiveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let activeArg = args[0] as! Bool
        let allowReadyPreviewArg = args[1] as! Bool
        do {
          try api.setScrollActive(active: activeArg, allowReadyPreview: allowReadyPreviewArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setScrollActiveChannel.setMessageHandler(nil)
    }
    let readRenderCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.job_map.JobMapHostApi.readRenderCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readRenderCapabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.readRenderCapabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      readRenderCapabilitiesChannel.setMessageHandler(nil)
    }
    let disposeFramesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.job_map.JobMapHostApi.disposeFrames\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeFramesChannel.setMessageHandler { _, reply in
        do {
          try api.disposeFrames()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeFramesChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol JobMapFlutterApiProtocol {
  func frameProgress(frame frameArg: NativeMapFinalFrame, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func frameFinal(frame frameArg: NativeMapFinalFrame, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func rendererReset(completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class JobMapFlutterApi: JobMapFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: JobMapApiPigeonCodec {
    return JobMapApiPigeonCodec.shared
  }
  func frameProgress(frame frameArg: NativeMapFinalFrame, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.job_map.JobMapFlutterApi.frameProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([frameArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func frameFinal(frame frameArg: NativeMapFinalFrame, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.job_map.JobMapFlutterApi.frameFinal\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([frameArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func rendererReset(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.job_map.JobMapFlutterApi.rendererReset\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
