// Autogenerated from Pigeon (v26.1.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.cataqui.job_map

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object JobMapApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMapRenderRequest (
  val requestId: Long,
  val rendererSlot: Long,
  val widthPx: Long,
  val heightPx: Long,
  val widthPoints: Double,
  val heightPoints: Double,
  val nativeScale: Double,
  val previewScale: Double,
  val cameraLatitude: Double,
  val cameraLongitude: Double,
  val locationLatitude: Double,
  val locationLongitude: Double,
  val zoom: Double,
  val radiusMeters: Double,
  val radiusColorArgb: Long,
  val backgroundColorArgb: Long,
  val paddingBottomPoints: Double,
  val styleJson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMapRenderRequest {
      val requestId = pigeonVar_list[0] as Long
      val rendererSlot = pigeonVar_list[1] as Long
      val widthPx = pigeonVar_list[2] as Long
      val heightPx = pigeonVar_list[3] as Long
      val widthPoints = pigeonVar_list[4] as Double
      val heightPoints = pigeonVar_list[5] as Double
      val nativeScale = pigeonVar_list[6] as Double
      val previewScale = pigeonVar_list[7] as Double
      val cameraLatitude = pigeonVar_list[8] as Double
      val cameraLongitude = pigeonVar_list[9] as Double
      val locationLatitude = pigeonVar_list[10] as Double
      val locationLongitude = pigeonVar_list[11] as Double
      val zoom = pigeonVar_list[12] as Double
      val radiusMeters = pigeonVar_list[13] as Double
      val radiusColorArgb = pigeonVar_list[14] as Long
      val backgroundColorArgb = pigeonVar_list[15] as Long
      val paddingBottomPoints = pigeonVar_list[16] as Double
      val styleJson = pigeonVar_list[17] as String?
      return NativeMapRenderRequest(requestId, rendererSlot, widthPx, heightPx, widthPoints, heightPoints, nativeScale, previewScale, cameraLatitude, cameraLongitude, locationLatitude, locationLongitude, zoom, radiusMeters, radiusColorArgb, backgroundColorArgb, paddingBottomPoints, styleJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      rendererSlot,
      widthPx,
      heightPx,
      widthPoints,
      heightPoints,
      nativeScale,
      previewScale,
      cameraLatitude,
      cameraLongitude,
      locationLatitude,
      locationLongitude,
      zoom,
      radiusMeters,
      radiusColorArgb,
      backgroundColorArgb,
      paddingBottomPoints,
      styleJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeMapRenderRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return JobMapApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMapFrames (
  val textureId: Long,
  val widthPx: Long,
  val heightPx: Long,
  val previewTextureId: Long,
  val previewWidthPx: Long,
  val previewHeightPx: Long,
  val isFinal: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMapFrames {
      val textureId = pigeonVar_list[0] as Long
      val widthPx = pigeonVar_list[1] as Long
      val heightPx = pigeonVar_list[2] as Long
      val previewTextureId = pigeonVar_list[3] as Long
      val previewWidthPx = pigeonVar_list[4] as Long
      val previewHeightPx = pigeonVar_list[5] as Long
      val isFinal = pigeonVar_list[6] as Boolean
      return NativeMapFrames(textureId, widthPx, heightPx, previewTextureId, previewWidthPx, previewHeightPx, isFinal)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textureId,
      widthPx,
      heightPx,
      previewTextureId,
      previewWidthPx,
      previewHeightPx,
      isFinal,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeMapFrames) {
      return false
    }
    if (this === other) {
      return true
    }
    return JobMapApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMapFinalFrame (
  val requestId: Long,
  val rendererSlot: Long,
  val textureId: Long,
  val widthPx: Long,
  val heightPx: Long,
  val previewTextureId: Long,
  val previewWidthPx: Long,
  val previewHeightPx: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMapFinalFrame {
      val requestId = pigeonVar_list[0] as Long
      val rendererSlot = pigeonVar_list[1] as Long
      val textureId = pigeonVar_list[2] as Long
      val widthPx = pigeonVar_list[3] as Long
      val heightPx = pigeonVar_list[4] as Long
      val previewTextureId = pigeonVar_list[5] as Long
      val previewWidthPx = pigeonVar_list[6] as Long
      val previewHeightPx = pigeonVar_list[7] as Long
      return NativeMapFinalFrame(requestId, rendererSlot, textureId, widthPx, heightPx, previewTextureId, previewWidthPx, previewHeightPx)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      rendererSlot,
      textureId,
      widthPx,
      heightPx,
      previewTextureId,
      previewWidthPx,
      previewHeightPx,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeMapFinalFrame) {
      return false
    }
    if (this === other) {
      return true
    }
    return JobMapApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeMapCapabilities (
  val lowMemory: Boolean,
  val lowRamDevice: Boolean,
  val availableMemoryBytes: Long,
  val totalMemoryBytes: Long,
  val processorCount: Long,
  val thermalState: Long,
  val maxRendererSlots: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeMapCapabilities {
      val lowMemory = pigeonVar_list[0] as Boolean
      val lowRamDevice = pigeonVar_list[1] as Boolean
      val availableMemoryBytes = pigeonVar_list[2] as Long
      val totalMemoryBytes = pigeonVar_list[3] as Long
      val processorCount = pigeonVar_list[4] as Long
      val thermalState = pigeonVar_list[5] as Long
      val maxRendererSlots = pigeonVar_list[6] as Long
      return NativeMapCapabilities(lowMemory, lowRamDevice, availableMemoryBytes, totalMemoryBytes, processorCount, thermalState, maxRendererSlots)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lowMemory,
      lowRamDevice,
      availableMemoryBytes,
      totalMemoryBytes,
      processorCount,
      thermalState,
      maxRendererSlots,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NativeMapCapabilities) {
      return false
    }
    if (this === other) {
      return true
    }
    return JobMapApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class JobMapApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMapRenderRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMapFrames.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMapFinalFrame.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeMapCapabilities.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeMapRenderRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeMapFrames -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativeMapFinalFrame -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeMapCapabilities -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface JobMapHostApi {
  fun render(request: NativeMapRenderRequest, callback: (Result<NativeMapFrames>) -> Unit)
  fun releaseTexture(textureId: Long)
  fun setScrollActive(active: Boolean, allowReadyPreview: Boolean)
  fun readRenderCapabilities(): NativeMapCapabilities
  fun disposeFrames()

  companion object {
    /** The codec used by JobMapHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      JobMapApiPigeonCodec()
    }
    /** Sets up an instance of `JobMapHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: JobMapHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.job_map.JobMapHostApi.render$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as NativeMapRenderRequest
            api.render(requestArg) { result: Result<NativeMapFrames> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(JobMapApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(JobMapApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.job_map.JobMapHostApi.releaseTexture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val textureIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.releaseTexture(textureIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              JobMapApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.job_map.JobMapHostApi.setScrollActive$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val activeArg = args[0] as Boolean
            val allowReadyPreviewArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setScrollActive(activeArg, allowReadyPreviewArg)
              listOf(null)
            } catch (exception: Throwable) {
              JobMapApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.job_map.JobMapHostApi.readRenderCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.readRenderCapabilities())
            } catch (exception: Throwable) {
              JobMapApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.job_map.JobMapHostApi.disposeFrames$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.disposeFrames()
              listOf(null)
            } catch (exception: Throwable) {
              JobMapApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class JobMapFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by JobMapFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      JobMapApiPigeonCodec()
    }
  }
  fun frameProgress(frameArg: NativeMapFinalFrame, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.job_map.JobMapFlutterApi.frameProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(frameArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(JobMapApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun frameFinal(frameArg: NativeMapFinalFrame, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.job_map.JobMapFlutterApi.frameFinal$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(frameArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(JobMapApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun rendererReset(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.job_map.JobMapFlutterApi.rendererReset$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(JobMapApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
